#Définition des types de nœuds

design:
  type: l3ls-evpn

# Configuration globale de la Fabric
pod_name: DC1
bgp_as: 65001 # ASN BGP de base (modèle eBGP ou iBGP géré par AVD)

# Plans d'adressage IP automatiques pour les interconnexions P2P et les Loopbacks
spine_mesh_as: 65000
loopback_ipv4_pool: 192.168.255.0/24
vtep_loopback_ipv4_pool: 192.168.254.0/24
uplink_ipv4_pool: 172.16.255.0/24

# Attribution des interfaces physiques dans EVE-NG
spine:
  defaults:
    platform: vEOS-lab
  # 🔧 Modification : Utilisation de tirets '-' pour créer une Liste
  nodes:
    - name: spine1
      id: 1
    - name: spine2
      id: 2

leaf:
  defaults:
    platform: vEOS-lab
    spanning_tree_mode: mstp
  # 🔧 Modification : Utilisation de tirets '-' pour créer une Liste
  nodes:
    - name: leaf1
      id: 11
      uplink_switches: [spine1, spine2]
      uplink_interfaces: [Ethernet1, Ethernet2] # Interfaces physiques sur LEAF1
      # 🔧 AJOUT : Interfaces correspondantes sur SPINE1 et SPINE2
      # Exemple : Ethernet1 de LEAF1 va sur Ethernet1 de SPINE1, et Ethernet2 va sur Ethernet1 de SPINE2
      uplink_switch_interfaces: [Ethernet1, Ethernet1]
    - name: leaf2
      id: 12
      uplink_switches: [spine1, spine2]
      uplink_interfaces: [Ethernet1, Ethernet2]
      uplink_switch_interfaces: [Ethernet2, Ethernet2]