name: "Arista AVD Deploy via Self-Hosted Runner"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  avd_deployment:
    name: "Générer et Déployer AVD"
    runs-on: ubuntu-latest

    steps:
      - name: "1. Récupérer le code du dépôt Git"
        uses: actions/checkout@v4

      - name: "2. Configurer Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: "3. Installer Ansible et les dépendances AVD"
        shell: powershell # 👈 Indique au runner d'utiliser PowerShell pour ce bloc
        run: |
          python -m venv venv
          .\venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          pip install ansible-core pyavd
          ansible-galaxy collection install arista.avd

      - name: "4. Exécuter le Playbook Arista AVD"
        shell: powershell # 👈 Indique au runner d'utiliser PowerShell pour ce bloc
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          .\venv\Scripts\Activate.ps1
          ansible-playbook -i inventory.yml dc1_playbook.yml --extra-vars "ansible_ssh_pass=${{ secrets.AVD_PASSWORD }}"
